version: '3.8'

services:
  app:
    image: anishkajan/secure-file-upload:latest
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - CLOUD_AWS_S3_BUCKET=${CLOUD_AWS_S3_BUCKET}
      - AWS_REGION=${AWS_REGION}
    restart: unless-stopped
